[project]
name = "fastapi-server"
version = "0.1.0"
description = "Basic FastAPI server"
readme = "README.md"
authors = [
    { name = "Krish Singh", email = "154358180+krishsingh120@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beanie>=2.2.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

